name: Release to npm

on:
  workflow_call: # reusable workflow
    inputs:
      node_version:
        description: "Node.js version"
        default: "20"
        required: false
      registry:
        description: "Registry (default npm)"
        default: "https://registry.npmjs.org/"
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: ${{ inputs.registry }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}